id: I6F4654A9
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T17:56:59.215957'
last_modified: '2022-06-19T17:56:59.215968'
parser: null
source_metadata:
  title: Ucchuṣma Series
  language: en
  description: 'Texts related to Ucchuṣma (sme brtsegs), a wrathful deity who is associated
    with the purification of defilements and whose name is sometimes given as Bhurkuṃkūṭa:'
  volume:
    f671B:
      title: A Daily Practice of Ucchuṣma
      base_file: f671B.txt
      order: 1
      parent: Sādhanas
    f7244:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      base_file: f7244.txt
      order: 2
      parent: Sādhanas
    fFAE6:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      base_file: fFAE6.txt
      order: 3
      parent: Sādhanas
    f2DFD:
      title: Dispeller of All Samaya Corruptions and Pollutions
      base_file: f2DFD.txt
      order: 4
      parent: Practices
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
